### ISSUE TITLE
Demo app crashes on Android after selecting "Create download task"

### ISSUE THREAD

**Issue by stevenz2143** [THEOplayer/react-native-theoplayer#455]
https://github.com/user-attachments/assets/38016bfa-99aa-4e74-ad14-309ba10d1ad2

**Logs:**
```
FATAL EXCEPTION: main
Process: com.reactnativetheoplayer, PID: 5273
com.tns.NativeScriptException: Calling js method init failed
TypeError: Cannot read property 'toJson' of undefined
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(SourceFile:76)
	at com.tns.Runtime.callJSMethodImpl(SourceFile:10)
	at com.tns.Runtime.callJSMethod(SourceFile:14)
	at com.tns.Runtime.callJSMethod(SourceFile:2)
	at com.tns.Runtime.callJSMethod(SourceFile:1)
	at com.theoplayer.android.core.sbggen.cache.CoreSourceCacherBridge.init(SourceFile:2)
	at com.theoplayer.android.internal.cache.CachingTaskImpl.<init>(SourceFile:82)
	at com.theoplayer.android.internal.cache.a.createTask(SourceFile:2)
	at com.theoplayer.cache.CacheModule.createTask$lambda$18(CacheModule.kt:178)
	at com.theoplayer.cache.CacheModule.$r8$lambda$NuMtEqs__2BiPiEkLCJEeQIGUKI(Unknown Source:0)
	at com.theoplayer.cache.CacheModule$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by ceyhun-o** [comment]
Hi @stevenz2143,

As also mentioned on our Service Desk, this issue is fixed on the underlying THEOplayer Android SDK 8.6.0, which was released yesterday.

Can you please give it a try and let us know if you are still seeing a similar crash?

**Comment by ceyhun-o** [comment]
Hi @stevenz2143,

Closing this issue as you confirmed on our Service Desk that 8.6.0 fixes this.
